from __future__ import annotations

import html
import json
import re
from datetime import date
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from .config import NewsletterConfig


STYLE = """
body { font-family: Georgia, 'Times New Roman', serif; max-width: 720px; margin: 0 auto; padding: 24px; line-height: 1.58; color: #1b1b1b; font-size: 17px; }
h1 { color: #7a1f1f; font-size: 30px; border-bottom: 3px solid #7a1f1f; padding-bottom: 8px; margin-bottom: 8px; }
.meta { color: #666; font-size: 13px; margin-bottom: 24px; }
h2 { color: #7a1f1f; font-size: 19px; letter-spacing: .02em; border-bottom: 1px solid #d8d8d8; padding-bottom: 5px; margin-top: 30px; }
a { color: #7a1f1f; text-decoration: none; border-bottom: 1px dotted #7a1f1f; }
p { margin: 0 0 18px; }
.note, .quick-take { background: #f6f6f6; border-left: 4px solid #7a1f1f; padding: 14px 18px; margin: 22px 0; }
.rapid-fire { font-size: 15px; }
.footer { margin-top: 40px; padding-top: 16px; border-top: 2px solid #7a1f1f; color: #666; font-size: 13px; text-align: center; }
"""


def html_to_plain(html_content: str) -> str:
    text = re.sub(r"(?is)<style.*?</style>|<script.*?</script>|<head.*?</head>", "", html_content)
    text = re.sub(r'(?is)<a[^>]*href=["\']([^"\']+)["\'][^>]*>(.*?)</a>', r"\2 (\1)", text)
    text = re.sub(r"(?is)<br\s*/?>", "\n", text)
    text = re.sub(r"(?is)</(p|li|h[1-6]|div)>", "\n\n", text)
    text = re.sub(r"(?is)<li[^>]*>", "- ", text)
    text = re.sub(r"(?s)<[^>]+>", "", text)
    text = html.unescape(text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def _wrap_document(config: NewsletterConfig, body: str, *, title_suffix: str = "") -> str:
    title = html.escape(config.name)
    today_date = date.today()
    today = f"{today_date.strftime('%B')} {today_date.day}, {today_date.year}"
    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>{STYLE}</style>
</head>
<body>
  <h1>{title}{html.escape(title_suffix)}</h1>
  <div class="meta">{today}</div>
  {body}
  <div class="footer">Generated by Scientific Newsletter. Review before clinical redistribution.</div>
</body>
</html>
"""


def render_prose(config: NewsletterConfig, prose: Dict[str, Any]) -> str:
    parts: List[str] = []
    note = prose.get("editor_note") or prose.get("editors_note")
    if note:
        parts.append(f'<div class="note">{note}</div>')
    for section in prose.get("sections", []):
        name = html.escape(str(section.get("name", "Section")))
        section_html = str(section.get("html") or "")
        css_class = ' class="rapid-fire"' if name.lower() == "rapid fire" else ""
        parts.append(f"<h2>{name}</h2>\n<div{css_class}>{section_html}</div>")
    quick_take = prose.get("quick_take")
    if quick_take:
        parts.append(f'<h2>Quick Take</h2>\n<div class="quick-take">{quick_take}</div>')
    return _wrap_document(config, "\n".join(parts))


def render_prepared_preview(config: NewsletterConfig, prepared: Dict[str, Any]) -> str:
    parts = [
        '<div class="note"><p>This is a dry-run reading-list preview. Use the draft command or Codex to write final prose before sending.</p></div>'
    ]
    for section in prepared.get("sections", []):
        parts.append(f"<h2>{html.escape(section.get('name', 'Section'))}</h2>")
        for paper in section.get("papers", []):
            title = html.escape(str(paper.get("title", "Untitled")))
            url = html.escape(str(paper.get("url", "")))
            journal = html.escape(str(paper.get("journal", "Unknown journal")))
            abstract = html.escape(str(paper.get("abstract", ""))[:500])
            parts.append(f'<p><strong><a href="{url}">{title}</a></strong><br><em>{journal}</em><br>{abstract}</p>')
    rapid = prepared.get("rapid_fire", {})
    if rapid.get("papers"):
        parts.append("<h2>Rapid Fire</h2><ul class=\"rapid-fire\">")
        for paper in rapid.get("papers", []):
            title = html.escape(str(paper.get("title", "Untitled")))
            url = html.escape(str(paper.get("url", "")))
            parts.append(f'<li><strong><a href="{url}">{title}</a></strong></li>')
        parts.append("</ul>")
    return _wrap_document(config, "\n".join(parts), title_suffix=" Preview")


def _prepared_by_url(prepared: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    lookup = {}
    for section in prepared.get("sections", []):
        for paper in section.get("papers", []):
            if paper.get("url"):
                row = dict(paper)
                row["_section"] = section.get("name")
                lookup[paper["url"]] = row
    for paper in prepared.get("rapid_fire", {}).get("papers", []):
        if paper.get("url"):
            row = dict(paper)
            row["_section"] = "Rapid Fire"
            lookup[paper["url"]] = row
    return lookup


def extract_sent_papers(prepared: Dict[str, Any], prose: Dict[str, Any]) -> List[Dict[str, Any]]:
    lookup = _prepared_by_url(prepared)
    joined_html = "\n".join(
        [str(prose.get("editor_note") or prose.get("editors_note") or "")]
        + [str(section.get("html") or "") for section in prose.get("sections", [])]
        + [str(prose.get("quick_take") or "")]
    )
    urls = re.findall(r'href=["\']([^"\']+)["\']', joined_html, flags=re.IGNORECASE)
    sent = []
    seen = set()
    for url in urls:
        if url in seen or url not in lookup:
            continue
        seen.add(url)
        paper = lookup[url]
        sent.append(
            {
                "title": paper.get("original_title") or paper.get("title"),
                "original_title": paper.get("original_title") or paper.get("title"),
                "url": paper.get("url"),
                "doi": paper.get("doi") or "",
                "journal": paper.get("journal") or "",
                "section": paper.get("_section") or "",
            }
        )
    return sent


def write_rendered(
    html_content: str,
    *,
    output_dir: Path = Path("output"),
    basename: str = "scientific-newsletter",
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{basename}-{date.today().isoformat()}.html"
    path.write_text(html_content, encoding="utf-8")
    return path


def write_sent_papers(sent_papers: Iterable[Dict[str, Any]], path: Path = Path("output/sent-papers.json")) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(list(sent_papers), indent=2), encoding="utf-8")
    return path
